service: hms-email-service

provider:
  name: aws
  runtime: python3.9
  stage: dev
  region: us-east-1
  environment:
    SMTP_HOST: ${env:SMTP_HOST, 'smtp.gmail.com'}
    SMTP_PORT: ${env:SMTP_PORT, '587'}
    SMTP_USER: ${env:SMTP_USER, ''}
    SMTP_PASSWORD: ${env:SMTP_PASSWORD, ''}
    SENDER_EMAIL: ${env:SENDER_EMAIL, ''}

functions:
  sendEmail:
    handler: handler.send_email_handler
    events:
      - http:
          path: email/send
          method: post
          cors: true

plugins:
  - serverless-offline
